### ISSUE TITLE
401 - invalid authenticaton

### ISSUE THREAD

**Issue by gnostis** [tanaikech/RunAll#1]
Followed all instructions (scripts.run), tried different accounts, but still getting:

```
[20-02-16 05:07:54:803 PST] [{
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}
, {
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}
]
```
Projects linked, script saved, authorization completed, API enabled everywhere.

**Comment by nathang21** [comment]
I also am running into this issue.

I think the problem is the documentation auth flow provided here [1] explains how to LINK the cloud project, and CREATE a credential. However it doesn't outline, how to USE the credential with this library. 

I'm trying to figure this out myself, but i'm not seeing any place to pass the OAuth Client ID

[1] https://gist.github.com/tanaikech/e945c10917fac34a9d5d58cad768832c

**Comment by nathang21** [comment]
Update: Made some progress (401 error --> 404 error).

Using the same example as above, I had to modify the request and add the undocumented `accessToken` parameter.

Ex.
````
function myFunction(e) {
  Utilities.sleep(1000);
  return e;
}

function mainRun() {
  // Please set "workers.length < 30".
  token = ScriptApp.getOAuthToken();
  var workers = [
    {
      functionName: "myFunction",
      arguments: ["request1"],
      accessToken: token
    },
    {
      functionName: "myFunction",
      arguments: ["request2"],
      accessToken: token
    }
  ];
  var results = RunAll.Do(workers); // Using this library
  console.log(results);
}
````
Error: 
```
message: "[{
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "status": "NOT_FOUND"
  }
}
, {
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "status": "NOT_FOUND"
  }
}
```

**Comment by nathang21** [comment]
I was only able to get that response 404 response once. After all I could get was empty responses:
`Results: [ {}, {} ]`

Just for the heck of it, I decided to try using Version 1 of the Library. I ran my function again and it worked.

Solution Summary:
1. Add auth token parameter.
2. Switch Library to v1

Caevet:
3. The results object is always an array full of blank objects for me, but due to other logging statements I confirmed my worker functions are actually executing, just not returning their status correctly.

**Comment by tanaikech** [comment]
About `Switch Library to v1`, I would like to confirm it.

About `accessToken`, I used  at [https://github.com/tanaikech/RunAll#4-copy-and-paste-script-for-web-apps](https://github.com/tanaikech/RunAll#4-copy-and-paste-script-for-web-apps). But I noticed that this is not in the document. I deeply apologize for this.

About `The results object is always an array full of blank objects for me`, in your script, you use 

```
var results = RunAll.Do(workers); // Using this library
console.log(results);
```

When you use the following script, what result will you get? Because `RunAll.DoWebApps` returns `HTTPResponse[]`. So I thought that when `console.log` is used, "blank objects" is returned.

```
var results = RunAll.DoWebApps(workers);
results.forEach(function(r) {
  Logger.log(r.getContentText());  // or console.log(r.getContentText())
});
```

**Comment by nathang21** [comment]
Fantastic, thanks for the clarification. I totally overlooked that, I figured the HTTPResponse[] was only for WebApps.

I think this issue can be resolved now with the solutions here.

**Comment by tanaikech** [comment]
Thank you for replying. I confirm the script of this library and updated it. So now I updated to [v1.1.2](https://github.com/tanaikech/RunAll#update-history). Could you please confirm it? In this case, the following sample script in the document can be used for Apps Script API. The reason of this issue is that I had tested the library using the modified library which is not the published library. So I couldn't notice the issue. About this, I apologize here.

Also, I modified the document.

```javascript
function myFunction(e) {
  Utilities.sleep(1000);
  return e;
}

function main() {
  // Please set "workers.length < 30".
  var workers = [
    {
      functionName: "myFunction",
      arguments: ["request1"],
    },
    {
      functionName: "myFunction",
      arguments: ["request2"],
    },
  ];
  var results = RunAll.Do(workers); // Using this library
  Logger.log(results);
}
```

**Comment by nathang21** [comment]
@tanaikech Thank you yes I have confirmed v1.1.2 is now working as expected without manually setting the accessToken parameter.

**Comment by tanaikech** [comment]
Thank you for confirming it!
